import Link from "next/link";
import { redirect } from "next/navigation";
import { CalendarDays, Clock3, Coins } from "lucide-react";
import { createClient } from "@/lib/supabase/server";

export default async function DashboardTestingPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const { data: memberships } = await supabase.from("campaign_members").select("id,status,joined_at,testing_campaigns!inner(id,title,minimum_minutes,reward_credits,ends_at,status,projects!inner(name,slug,platform,icon_url))").eq("tester_id",user.id).order("joined_at",{ascending:false});
  const ids=(memberships??[]).map(m=>m.id); const { data:sessions }=ids.length?await supabase.from("test_sessions").select("campaign_member_id,minutes_tested").in("campaign_member_id",ids):{data:[] as {campaign_member_id:string;minutes_tested:number}[]};
  const totals=new Map<string,number>(); for(const s of sessions??[]) totals.set(s.campaign_member_id,(totals.get(s.campaign_member_id)??0)+s.minutes_tested);
  return <div><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-black">My testing</h2><p className="mt-1 text-soft">Log sessions and submit useful feedback.</p></div><Link href="/campaigns" className="btn-primary">Find campaigns</Link></div>
  {(memberships??[]).length===0?<div className="card p-10 text-center"><h3 className="text-2xl font-black">You have not joined a campaign yet</h3><p className="mt-3 text-soft">Join a live test to start building your tester history.</p><Link href="/campaigns" className="btn-primary mt-6">Browse campaigns</Link></div>:<div className="grid gap-5 lg:grid-cols-2">{(memberships??[]).map(m=>{const c=Array.isArray(m.testing_campaigns)?m.testing_campaigns[0]:m.testing_campaigns;if(!c)return null;const p=Array.isArray(c.projects)?c.projects[0]:c.projects;if(!p)return null;const days=c.ends_at?Math.max(0,Math.ceil((new Date(c.ends_at).getTime()-Date.now())/86400000)):null;const total=totals.get(m.id)??0;return <article key={m.id} className="card p-6"><div className="flex gap-4">{p.icon_url?<img src={p.icon_url} alt="" className="h-14 w-14 rounded-xl object-cover"/>:<div className="grid h-14 w-14 place-items-center rounded-xl bg-lime font-black text-ink">{p.name.charAt(0)}</div>}<div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan">{m.status.replaceAll("_"," ")}</p><h3 className="mt-1 text-2xl font-black">{c.title}</h3><p className="mt-1 text-sm text-soft">{p.name} · {p.platform}</p></div></div><div className="mt-5 flex flex-wrap gap-4 text-sm text-soft"><span className="flex items-center gap-2"><Clock3 size={16}/>{total}/{c.minimum_minutes} min</span><span className="flex items-center gap-2"><Coins size={16}/>{c.reward_credits} credits</span>{days!==null&&<span className="flex items-center gap-2"><CalendarDays size={16}/>{days} days left</span>}</div><Link href={`/dashboard/testing/${m.id}`} className="btn-primary mt-5 w-full">Open testing workspace</Link></article>})}</div>}</div>;
}
