import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { reviewFeedback } from "@/app/dashboard/testing/actions";

export default async function FeedbackReviewPage({params,searchParams}:{params:Promise<{projectId:string;campaignId:string}>;searchParams:Promise<{error?:string;success?:string}>}){
 const {projectId,campaignId}=await params; const messages=await searchParams; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login");
 const {data:project}=await supabase.from("projects").select("id,name,owner_id").eq("id",projectId).maybeSingle(); if(!project||project.owner_id!==user.id)notFound();
 const {data:campaign}=await supabase.from("testing_campaigns").select("id,title,reward_credits").eq("id",campaignId).eq("project_id",projectId).maybeSingle(); if(!campaign)notFound();
 const {data:members}=await supabase.from("campaign_members").select("id,status,joined_at,submitted_at,approved_at,profiles!campaign_members_tester_id_fkey(username,display_name,tester_reputation),feedback_reports(id,installation_success,crash_found,severity,what_worked,what_was_confusing,bug_details,performance_rating,stability_rating,usability_rating,overall_rating,review_note,feedback_attachments(id,file_url)),test_sessions(minutes_tested,device_name,os_version,notes)").eq("campaign_id",campaignId).order("joined_at",{ascending:false});
 return <div><div className="mb-6"><p className="text-sm font-bold uppercase tracking-[.2em] text-cyan">Developer review</p><h2 className="mt-2 text-3xl font-black">{campaign.title}</h2><p className="mt-2 text-soft">Review submitted reports for {project.name}.</p></div>{messages.success&&<div className="mb-5 rounded-xl border border-lime/30 bg-lime/10 p-4 text-sm text-lime">{messages.success}</div>}{messages.error&&<div className="mb-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{messages.error}</div>}
 {(members??[]).length===0?<div className="card p-10 text-center text-soft">No testers have joined yet.</div>:<div className="space-y-5">{(members??[]).map(m=>{const profile=Array.isArray(m.profiles)?m.profiles[0]:m.profiles;const report=Array.isArray(m.feedback_reports)?m.feedback_reports[0]:m.feedback_reports;const minutes=(m.test_sessions??[]).reduce((sum,s)=>sum+s.minutes_tested,0);return <article key={m.id} className="card p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xl font-black">{profile?.display_name||profile?.username||"Tester"}</p><p className="mt-1 text-sm text-soft">{minutes} minutes logged · status: {m.status.replaceAll("_"," ")}</p></div><span className="badge">Reward {campaign.reward_credits}</span></div>{!report?<p className="mt-5 rounded-xl bg-white/5 p-4 text-soft">This tester has not submitted final feedback yet.</p>:<><div className="mt-5 grid gap-4 sm:grid-cols-4">{[["Overall",report.overall_rating],["Performance",report.performance_rating],["Stability",report.stability_rating],["Ease of use",report.usability_rating]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-white/5 p-4"><p className="text-xs text-soft">{l}</p><p className="mt-1 text-2xl font-black">{String(v)}/5</p></div>)}</div><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-xl bg-white/5 p-5"><h3 className="font-black">What worked</h3><p className="mt-2 whitespace-pre-wrap text-soft">{report.what_worked}</p></div><div className="rounded-xl bg-white/5 p-5"><h3 className="font-black">What was confusing</h3><p className="mt-2 whitespace-pre-wrap text-soft">{report.what_was_confusing}</p></div></div>{report.bug_details&&<div className="mt-4 rounded-xl bg-white/5 p-5"><h3 className="font-black">Bug details · {report.severity}</h3><p className="mt-2 whitespace-pre-wrap text-soft">{report.bug_details}</p></div>}{(report.feedback_attachments??[]).length>0&&<div className="mt-5 grid gap-3 sm:grid-cols-3">{report.feedback_attachments.map(a=><a key={a.id} href={a.file_url} target="_blank" rel="noreferrer"><img src={a.file_url} alt="Feedback attachment" className="h-40 w-full rounded-xl object-cover"/></a>)}</div>}{m.status==="submitted"&&<form action={reviewFeedback.bind(null,m.id,campaignId,projectId)} className="mt-5 rounded-xl border border-white/10 bg-white/[0.03] p-5"><label><span className="label">Review note</span><textarea name="reviewNote" className="field min-h-24 resize-y" maxLength={1500}/></label><div className="mt-4 flex flex-wrap gap-3"><button name="decision" value="approve" className="btn-primary">Approve and award credits</button><button name="decision" value="reject" className="btn-secondary">Request changes</button></div></form>}</>}</article>})}</div>}</div>;
}
