import { redirect } from "next/navigation";
import { AlertTriangle, Download, KeyRound, ShieldAlert } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { changePassword, deleteAccount } from "./actions";
import { PasswordField, PasswordPairFields } from "@/components/password-field";

export default async function AccountSettingsPage({ searchParams }: { searchParams: Promise<{ error?: string; passwordError?: string; passwordSuccess?: string }> }) {
  const params=await searchParams; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/login");
  const providers=(user.identities||[]).map(identity=>identity.provider); const hasEmailPassword=providers.includes("email") || providers.length===0;
  const [{count:ownedProjects},{count:activeTests},{count:openDisputes}]=await Promise.all([
    supabase.from("projects").select("id",{count:"exact",head:true}).eq("owner_id",user.id),
    supabase.from("campaign_members").select("id",{count:"exact",head:true}).eq("tester_id",user.id).in("status",["joined","in_progress","submitted"]),
    supabase.from("feedback_disputes").select("id",{count:"exact",head:true}).eq("opened_by",user.id).eq("status","open")]);
  return <div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-cyan">Account security</p><h2 className="mt-2 text-3xl font-black">Account and data</h2><p className="mt-2 text-soft">Manage your sign-in security and permanent account actions.</p>
    <section className="card mt-6 p-6"><div className="flex items-start gap-3"><Download className="mt-1 text-cyan"/><div><h3 className="text-xl font-black">Your account summary</h3><p className="mt-2 text-sm text-soft">Signed in as {user.email}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-white/5 p-4"><p className="text-xs text-soft">Owned projects</p><p className="mt-1 text-2xl font-black">{ownedProjects||0}</p></div><div className="rounded-xl bg-white/5 p-4"><p className="text-xs text-soft">Active tests</p><p className="mt-1 text-2xl font-black">{activeTests||0}</p></div><div className="rounded-xl bg-white/5 p-4"><p className="text-xs text-soft">Open disputes</p><p className="mt-1 text-2xl font-black">{openDisputes||0}</p></div></div></section>
    <section id="change-password" className="card mt-6 p-6"><div className="flex items-start gap-3"><KeyRound className="mt-1 text-cyan"/><div><h3 className="text-xl font-black">Change password</h3><p className="mt-2 text-sm text-soft">Use a strong, unique password. Your password stays in Supabase Auth and is never stored in the Iconic Nexus database.</p></div></div>{params.passwordError&&<div className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-red-100">{params.passwordError}</div>}{params.passwordSuccess&&<div className="mt-5 rounded-xl border border-lime/30 bg-lime/10 p-4 text-lime">{params.passwordSuccess}</div>}
      {hasEmailPassword?<form action={changePassword} className="mt-6 space-y-4"><PasswordField name="currentPassword" label="Current password" autoComplete="current-password"/><PasswordPairFields passwordLabel="New password" confirmLabel="Confirm new password"/><button type="submit" className="btn-primary">Change password</button></form>:<div className="mt-5 rounded-xl border border-cyan/20 bg-cyan/5 p-4 text-sm text-soft">Your password is managed by your sign-in provider ({providers.join(", ")||"external provider"}). Use that provider to update it.</div>}
    </section>
    <section className="mt-6 rounded-2xl border border-red-400/30 bg-red-400/[0.06] p-6"><div className="flex items-start gap-3"><ShieldAlert className="mt-1 text-red-300"/><div><h3 className="text-xl font-black text-red-100">Delete account permanently</h3><p className="mt-2 leading-7 text-red-100/75">This removes your profile, projects, campaigns, uploads and access. Deletion is blocked while submitted feedback or unresolved disputes still exist.</p></div></div>{params.error&&<div className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-100">{params.error}</div>}<form action={deleteAccount} className="mt-6 space-y-4"><PasswordField name="password" label="Current password" autoComplete="current-password"/><label><span className="label">Type DELETE MY ACCOUNT</span><input name="confirmation" required className="field" placeholder="DELETE MY ACCOUNT"/></label><div className="flex items-start gap-3 rounded-xl bg-black/20 p-4 text-sm text-red-100/80"><AlertTriangle className="mt-0.5 shrink-0" size={18}/><p>This action cannot be undone. Export anything you need before continuing.</p></div><button type="submit" className="rounded-xl border border-red-400/40 bg-red-500/20 px-5 py-3 font-black text-red-100 hover:bg-red-500/30">Permanently delete my account</button></form></section>
  </div>;
}
